accounts/urls.py
from django.conf.urls import url

from django.views.generic.base import RedirectView

from .views import (
	UserDetailView,
	UserFollowView

	)

urlpatterns = [

	url(r'^(?P<pk>\d+)/$', UserDetailView.as_view(), name='detail'),
	url(r'^(?P<pk>\d+)/follow/$', UserFollowView.as_view(), name='follow/'),

]

tweetme/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

#from tweets.views import TweetListView
from .views import home

#from django.conf import settings
#from django.conf.urls.static import static


urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^$', home, name='home'),
    url(r'^profiles/', include('accounts.urls', namespace='profiles')),
	url(r'^tweet/', include('tweets.urls')),
    url(r'^api/tweet/', include('tweets.api.urls', namespace='tweet-api')),

]

if settings.DEBUG:
	urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

#if settings.DEBUG:
	#urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

tweets/api/urls.py
from django.conf.urls import url

from django.views.generic.base import RedirectView

from .views import (
	TweetCreateAPIView,
	TweetListAPIView
	)

urlpatterns = [

	url(r'^$', TweetListAPIView.as_view(), name='list'),
	url(r'^create/$', TweetCreateAPIView.as_view(), name='create'),

]

tweets/urls.py
from django.conf.urls import url

from .views import (
	tweet_detail_view, tweet_list_view, tweet_create_view
	)

urlpatterns = [
	#url(r'^create/$', TweetCreateView.as_view(), name='create'),
    url(r'^$', tweet_list_view, name='list'),
    url(r'^create$', tweet_create_view, name='create'),
    url(r'^(?P<pk>\d+)1/$', tweet_detail_view, name='detail'),
    



]

accounts/models.py
from django.conf import settings
from django.db import models
# Create your models here.


class UserProfile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name= 'profile')
	following = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name= 'followed_by')

	def _str_(self):
		return str(self.following.all().count())

tweets/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models

# Create your models here.

from .validators import validate_content

class Tweet(models.Model):
	user      = models.ForeignKey(settings.AUTH_USER_MODEL)
	content   = models.CharField(max_length=140, validators=[validate_content])
	updated   = models.DateTimeField(auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True)

	def _str_(self):
		return str(self.content)
	

	#def clean(self, *args, **kwargs):
	#	content = self.content
	#	if content == "abc":
	#		raise ValidationError("Content cannot be ABC")
	#		return super(Tweet, self).clean(*args, **kwargs)

tweets/forms.py
from django import forms


from .models import Tweet

class TweetModelForm(forms.ModelForm):
	class Meta:
		model = Tweet
		fields = [
			"user",
			"content"

		]

	#	def clean_content(self, *args, **kwargs):
	#		content = self.cleaned_data.get("content")
	#		if content == "abc":
	#			raise forms.ValidationError("Cannot be ABC")
	#		return content

accounts/views.py
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import DetailView

from .models import UserProfile

# Create your views here.
User = get_user_model()


class UserDetailView(DetailView):
	template_name ='accounts/user_detail.html'
	queryset = User.objects.all()



class UserFollowView(View):
	def get(self, request, username, *args, **kwargs):
		toggle_user = get_object_or_404(User, username_iexact=username)
		if request.user.is_authenticated():
			user_profile, created = UserProfile.objects.get_or_create(user=request.user)
			if toggle_user in user_profile.following.all():
				user_profile.following.remove(toggle_user)
			else:
				user_profile.following.add(toggle_user)

		return redirect("profiles:detail", username=username)

tweetme/views.py
from django.shortcuts import render


def home(request):
	return render(request, "home.html", {})

tweets/api/views.py
from rest_framework import generics
from rest_framework import permissions


from tweets.models import Tweet

from .pagination import StandardResultsPagination
from .serializers import TweetModelSerializer

class TweetCreateAPIView(generics.CreateAPIView):
	serializer_class = TweetModelSerializer
	permission_classes = [permissions.IsAuthenticated]

	def perform_create(self, serializer):
		serializer.save(user=self.request.user)

class TweetListAPIView(generics.ListAPIView):
	serializer_class = TweetModelSerializer
	pagination_class = StandardResultsPagination

	def get_queryset(self):
		qs = Tweet.objects.all().order_by("-timestamp")
		return Tweet.objects.all()

tweets/views.py
#from django import forms
#from django.forms.utils import ErrorList
from django.shortcuts import render
#from django.views.generic import DetailView, Listview, CreateView

# Create your views here.
from .forms import TweetModelForm
from .models import Tweet 
#Create

#class TweetCreateView(CreateView):
#	form_class = TweetModelForm
#	queryset = Tweet.objects.all()
#	form = TweetModelForm
#	fields = ['user', 'content']
#	def form valid(self, form):
#		if self.request.user.is_authenticated():
#			return super(TweetCreateView, self).form_valid(form)
#		else:
#			form_errors[forms.forms.NON_FIELD_ERRORS] = ErrorList(["User must be logged in to continue"])
#			return self.form_valid(form)

#Retrieve

#Update

#Delete


#List / Search
def tweet_create_view(request):
	form = TweetModelForm(request.POST or None)

	if form.is_valid():
		instance = form .save(commit=False)
		instance.user = request.user
		instance.save()

	context = {
		"form":form
	}
	return render(request, 'tweets/create_view.html', context)


def tweet_detail_view(request, id=1):
	obj = Tweet.objects.get(id=id)
	print(obj)
	context = {
		"object": obj
	}
	return render(request, "tweets/detail_view.html", context)

def tweet_list_view(request):
	queryset = Tweet.objects.all()
	print(queryset)
	for obj in queryset:
		print(obj.content)
	context = {
		"object_list": queryset
	}
	return render(request, "tweets/list_view.html", context)

accounts/templates/accounts/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title%}Tweetme.co{% endblock title%}</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" > 
    <!-- link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" -->


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class='container'>
      {% include "navbar.html" %}
      {% block content %}
      {% endblock content %}

    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script  -->
  </body>
</html>

accounts/templates/accounts/user_detail.html
{% extends "base.html" %}



{% block content %}
<div class='row'>
	<div class='col-sm-3 col-xs-12' style='background-color:green;'>
		<h1>{{ object.username }} </h1>
	</div>
	<div class='col-sm-9 col-xs-12'>
		<h1>Tweets</h1>
		{% for tweet in object.tweet_set.all %}
		{{ tweet }}<br/>

		{% endfor %}


		<hr/>

		<h1>Following</h1>
		
		{% for user in object.profile.following.all %}
		<a href='/{{ user.username }}'>{{ user.username }}</a><br/>
		{% empty %}
		<h4>Not following any users </h4>

		{% endfor %}

		<hr/>

		<h1>Followed by</h1>
		
		{% for profile in object.followed_by.all %}
		<a href='/{{ profile.user.username }}'>{{ profile.user.username }}</a><br/>
		{% empty %}
		<h4>Not followed by any users </h4>
		{% endfor %}

	</div>

</div>

{% endblock content %}

templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title%}Tweetme.co{% endblock title%}</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" > 
    <!-- link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" -->


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class='container'>
      {% include "navbar.html" %}
      {% block content %}
      {% endblock content %}

    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script  -->
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}{{ block.super }} | Welcome{% endblock title %}



{% block content %}
<h1>Hello, World Again </h1>
{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Tweetme</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
      </ul>
      
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

tweets/templates/tweets/create_view.html
<form class = 'form' method = 'POST' action = "">
	{% csrf_token %}
	{{ form.as_p }}
	<input type = "submit" value = "Tweet" />
</form>

tweets/templates/tweets/detail_view.html
<!-- {{ object }} -->
{% extends "base.html" %}


{% block content %}
<div class='row'>
	<div class='col-sm-1' style='background-color:red;'>
		{{ object.user }}
	</div>
	<div class='col-sm-1' style='background-color:yellow;'>
		{{ object.user }}
	</div>
	<div class='col-sm-1' style='background-color:green;'>
		{{ object.user }}
	</div>
	<div class='col-sm-1' style='background-color:blue;'>
		{{ object.user }}
	</div>

	{{ object.content }}<br/>
	<br/>
	{{ object.timestamp|timesince }}

</div>




{% endblock content %}

tweets/templates/tweets/list_view.html
{% for object in object_list %}
	<p>{{ object.content }}<br/>
	{{ object.user }}<br/>
	{{ object.timestamp }}<br/>
	{{ object.timestamp|timesince }} ago</p><br/><br/>

{% endfor %}